Added logic new flag for forwarding traffic to remote host

diff --git a/l2snoop b/l2snoop
--- a/l2snoop
+++ b/l2snoop
@@ -17,7 +17,7 @@ echo "Transparent man in the middle over an ethernet bridge. The script will ass
 
 echo "";
 
-while getopts "gh" opt; do
+while getopts "ghrd" opt; do
 
 	case $opt in
 		
@@ -25,7 +25,7 @@ while getopts "gh" opt; do
 		echo "L2Snoop help"
 		echo "L2Snoop is a tool to help set up a man in the middle bridge for intercepting devices that may not be proxy aware or talk to other devices on the local network"
 		echo "-h  Prints out this help menu"
-		echo "-g  Initiates guided mode which will help walk through setting up the bridge and ports to be redirected"
+		echo "-g  Initiates guided mode which will help walk through setting up the bridge and ports to be redirected on the local machine"
 		echo "-d  deletes the bridge and flushes the nat table in iptables and the broute table in ebtables"
 		;;
 
@@ -100,6 +100,7 @@ while getopts "gh" opt; do
 			route add default gw $gateway dev br0
 		else
 			dhclient br0
+			ipaddr=$(ifconfig br0 | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
 		fi	
 
 		echo 'Please enter the **number of ports** you would like to redirect'
@@ -128,10 +129,115 @@ while getopts "gh" opt; do
 		echo "You should be set to intercept. Make sure you have your interceptors listening on $ipaddr not localhost. Happy sniffing."
 
 		;;
+	r)
+
+		if ! [ $(id -u) = 0 ]; then
+		   echo "Sorry but to do all the cool stuff you need to run this as root"
+		   exit 1
+		fi
+
+		echo "Checking dependancies...";
+
+		hash brctl &> /dev/null
+		if [ $? -eq 1 ]; then
+		    echo >&2 "brctl not found. Please install bridge-utils";
+		    exit 1
+		fi
+
+		hash iptables &> /dev/null
+		if [ $? -eq 1 ]; then
+		    echo >&2 "iptables not found. Please install iptables"
+		    exit 1
+		fi
+
+		hash ebtables &> /dev/null
+		if [ $? -eq 1 ]; then
+		    echo >&2 "ebtables not found. Please install ebtables"
+		    exit 1
+		fi
+
+		echo "Looks like you should be okay..."
+
+		echo "Enter the first interface to bridge:"
+		read interface1
+		echo "Enter the second interface:"
+		read interface2
+		echo "Would you like to set up the bridge with DHCP? (recommended) Y/n"
+		read dhcp
+		if [[ $dhcp =~ ^n|N$ ]]; then
+			echo "Enter the network IP address to give the bridge:"
+			read ip
+
+			if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+				ipaddr=$ip
+			else
+				echo "The ip entered doesnt seem valid... exiting"
+				exit 1
+			fi	
+
+			echo "Enter the default gateway for the network:"
+			read gate
+
+			if [[ $gate =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+				gateway=$gate
+			else
+				echo "The ip entered doesnt seem valid... exiting"
+				exit 1
+			fi
+		fi
+
+
+		#Setting up the bridge
+		ifconfig $interface1 0.0.0.0 promisc up
+		ifconfig $interface2 0.0.0.0 promisc up
+		brctl addbr br0
+		brctl addif br0 $interface1
+		brctl addif br0 $interface2
+		ip link set br0 up
+		if [[ $dhcp =~ ^n|N$ ]]; then
+			ip addr add $ipaddr/24 brd + dev br0
+			route add default gw $gateway dev br0
+		else
+			dhclient br0
+			ipaddr=$(ifconfig br0 | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
+		fi
+
+		echo 'Please enter the destination host where you plan on running you intercepter'
+		read destHost	
+
+		echo 'Please enter the **number of ports** you would like to redirect'
+		read number
+		for ((i = 1; i <= number; i++))
+		do 
+			echo "Enter the destination port to redirect:";
+			read srcPort
+			echo ""
+			echo "Enter the port on local host you would like $srcPort redirected to:"
+			read destPort
+			echo ""
+			echo "Redirecting *:$srcPort ---> $destHost:$destPort"
+			echo ""
+
+			#here is where the magic happens
+			ebtables -t broute -A BROUTING -p IPv4 --ip-protocol 6 --ip-destination-port $srcPort -j redirect --redirect-target ACCEPT
+			iptables -t nat -A PREROUTING -i br0 -p tcp --dport $srcPort -j DNAT --to-destination $destHostPort
+			iptables -t nat -A FORWARD -p tcp -d $destHost --dport $destPort -j ACCEPT
+			iptables -t nat -A POSTROUTING -p tcp -d $destHost -dport $destPort -j SNAT --to-source $ipaddr
+
+		done
+
+		echo "Here are your iptables and ebtables rules:"
+		ebtables -t broute -L
+		iptables -t nat -L
+
+		echo "You should be set to intercept. Make sure you have your interceptors listening on "$destHost". Happy sniffing."
+
+		;;
 
 	d)
 		echo "Cleaning up..."
-		ifconfig br0 down
+		ip link set br0 down
+		brctl delbr br0
 		ebtables -t broute -F
 		iptables -t nat -F
 		;;	
